# Generated by Django 5.1.3 on 2025-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_verified_profile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
