# Generated by Django 5.1.3 on 2025-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
