# Generated by Django 5.1.3 on 2025-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
